name = "miguelmachado" # Replace with your desired worker name
main = ".open-next/server-fn/index.js"
compatibility_date = "2023-10-30" # Or a more recent date

[site]
bucket = ".open-next/assets" # Tells wrangler where the static assets are

[[kv_namespaces]]
binding = "NEXT_CACHE" # Must match kvBinding in open-next.config.js
id = "c73f674b9bde475fb17fc4d137deef61" # Replace with your actual KV Namespace ID from Cloudflare dashboard
# preview_id = "YOUR_KV_NAMESPACE_PREVIEW_ID" # Optional: for local wrangler dev preview
